package Timetable;

public enum NameParameters {
    MIN_COUNT_OF_NODES,
    MAX_COUNT_OF_NODES,
    MIN_LENGTH_NAME_SHIP,
    MAX_LENGTH_NAME_SHIP,
    PERFORMANCE_LOOSE,
    PERFORMANCE_LIQUID,
    PERFORMANCE_CONTAINER,
    MIN_LOOSE_SHIP,
    MAX_LOOSE_SHIP,
    MIN_LIQUID_SHIP,
    MAX_LIQUID_SHIP,
    MIN_CONTAINER_SHIP,
    MAX_CONTAINER_SHIP
}
